spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tehno_seti_db
    username: tehno_user
    password: Hfleuf7&
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true